import { requestAgentAi } from './client.js';
import { AI_PLUGIN_CSS } from './panel.css.js';
import { AgentAiPluginState } from './state.js';

function el(tag, cls, text) {
    const node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text != null) node.textContent = text;
    return node;
}

function injectCss() {
    if (document.getElementById('agent-ai-plugin-style')) return;
    const style = document.createElement('style');
    style.id = 'agent-ai-plugin-style';
    style.textContent = AI_PLUGIN_CSS;
    document.head.appendChild(style);
}

async function copyText(text) {
    if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(text);
        return;
    }
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.setAttribute('readonly', 'readonly');
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
}

class AgentAiPluginPanel {
    constructor() {
        this.state = new AgentAiPluginState();
        this.open = false;
        this.loading = '';
        this.notice = '';
        this.error = '';
        this.build();
        this.render();
    }

    build() {
        injectCss();

        const toggle = el('button', 'ap-toggle', 'AI 插件');
        toggle.title = 'AI Plugin';
        toggle.addEventListener('click', () => {
            this.open = !this.open;
            this.root.classList.toggle('ap-collapsed', !this.open);
            toggle.classList.toggle('ap-toggle-on', this.open);
            if (this.open) this.autoGenerate();
        });
        document.body.appendChild(toggle);
        this.toggleBtn = toggle;

        const root = el('aside', 'ap-root ap-collapsed');
        const header = el('div', 'ap-header');
        header.appendChild(el('div', 'ap-title', 'AI 插件'));
        header.appendChild(el('div', 'ap-sub', '自动旁白，按需补内容'));
        root.appendChild(header);

        this.body = el('div', 'ap-body');
        root.appendChild(this.body);
        document.body.appendChild(root);
        this.root = root;
    }

    reset() {
        this.state.reset();
        this.notice = '';
        this.error = '';
        this.render();
    }

    updateFromStep(payload) {
        this.state.addStep(payload?.ir, payload?.summary);
        this.render();
        if (this.open) this.autoGenerate();
    }

    async autoGenerate() {
        const key = this.state.latestKey();
        if (!key || this.loading || this.state.autoGeneratedFor === key) return;
        this.state.autoGeneratedFor = key;
        await this.runAi('snapshot', { silent: true });
    }

    section(title, text, cls = '') {
        const section = el('section', 'ap-section');
        section.appendChild(el('h3', 'ap-h3', title));
        section.appendChild(el('div', `ap-card ${cls}`.trim(), text));
        this.body.appendChild(section);
        return section;
    }

    button(label, title, onClick, options = {}) {
        const btn = el('button', options.warm ? 'ap-btn ap-btn-warm' : 'ap-btn', label);
        btn.title = title;
        btn.disabled = !!options.disabled || !!this.loading;
        btn.addEventListener('click', async () => {
            await onClick();
        });
        return btn;
    }

    async runAi(mode, options = {}) {
        if (!this.state.latest) {
            this.notice = '';
            this.error = '先开始一局，AI 才有东西可读。';
            this.render();
            return;
        }

        this.loading = mode;
        if (!options.silent) {
            this.notice = '';
            this.error = '';
        }
        this.render();
        try {
            const result = await requestAgentAi({
                mode,
                payload: this.state.context(),
            });
            this.state.lastMeta = result.meta || null;
            this.applyResult(mode, result);
            if (!options.silent) this.notice = 'AI 已生成';
        } catch (error) {
            console.error('[agent-ai-plugin] request failed:', error);
            if (!options.silent) this.error = error.message || 'AI 生成失败';
        } finally {
            this.loading = '';
            this.render();
        }
    }

    applyResult(mode, result) {
        if (mode === 'snapshot') {
            for (const key of ['narration', 'recap', 'share', 'delta', 'branch']) {
                if (result[key]) this.state[key] = result[key];
            }
            return;
        }
        if (mode === 'expand') {
            this.state.extra = Array.isArray(result.extra) ? result.extra : [];
            return;
        }
        if (mode === 'death') {
            this.state.deaths = Array.isArray(result.deaths) ? result.deaths : [];
            return;
        }
        if (mode === 'branch') {
            this.state.branch = result.branch || result.text || '';
            if (Array.isArray(result.extra)) this.state.extra = result.extra;
            return;
        }
        if (mode === 'candidates') {
            this.state.candidates = Array.isArray(result.candidates) ? result.candidates : [];
            return;
        }
        this.state[mode] = result[mode] || result.text || '';
    }

    render() {
        this.body.innerHTML = '';
        if (this.loading) this.body.appendChild(el('div', 'ap-notice', this.loading === 'snapshot' ? 'AI 正在顺手读这一局。' : 'AI 正在补一块内容。'));
        if (this.notice) this.body.appendChild(el('div', 'ap-notice', this.notice));
        if (this.error) this.body.appendChild(el('div', 'ap-notice ap-error', this.error));

        this.renderStatus();
        this.section('旁白', this.state.narration || '打开后会自动生成一句当前旁白。');
        this.section('故事复盘', this.state.recap || '通关后这里会更完整；现在也会先给阶段复盘。');
        this.section('截图分享', this.state.share || '这里会生成一句适合截图和群聊的短句。', 'ap-card-warm');
        this.section('属性解读', this.state.delta || '这里会把数值变化翻译成人话。');
        this.section('轻量支线', this.state.branch || '这里会放一张不进入主线的 AI 支线卡。');
        this.renderExpanded();
        this.renderActions();
        this.renderMeta();
    }

    renderStatus() {
        const latest = this.state.latest;
        const section = el('section', 'ap-section');
        section.appendChild(el('h3', 'ap-h3', '当前片段'));
        const status = el('div', 'ap-status');
        status.innerHTML = latest
            ? `<strong>${latest.age} 岁 · ${latest.stage}</strong><br>${latest.text || '这一年很安静，但日志不会撒谎。'}`
            : '<strong>未启动</strong><br>开始一局后，这里会读取当前 Agent 的人生片段。';
        section.appendChild(status);
        this.body.appendChild(section);
    }

    renderExpanded() {
        const section = el('section', 'ap-section');
        section.appendChild(el('h3', 'ap-h3', '补充内容'));
        const list = el('div', 'ap-list');
        if (!this.state.extra.length && !this.state.deaths.length && !this.state.candidates.length) {
            list.appendChild(el('div', 'ap-empty', '可以按需补一点：多讲两句、加一张支线、补几个死法，或者生成候选素材。'));
        }
        for (const item of this.state.extra) {
            const row = el('div', 'ap-item');
            row.appendChild(el('div', 'ap-item-title', item.title || item.kind || '更多内容'));
            row.appendChild(el('div', 'ap-item-text', item.text || item.description || ''));
            list.appendChild(row);
        }
        for (const item of this.state.deaths) {
            const row = el('div', 'ap-item');
            row.appendChild(el('div', 'ap-item-title', item.title || item.kind || '死法候选'));
            row.appendChild(el('div', 'ap-item-text', item.text || item.description || ''));
            list.appendChild(row);
        }
        for (const candidate of this.state.candidates) {
            const row = el('div', 'ap-item');
            row.appendChild(el('div', 'ap-item-title', candidate.title || candidate.kind || '候选素材'));
            row.appendChild(el('div', 'ap-item-text', candidate.text || candidate.description || ''));
            if (candidate.reason) row.appendChild(el('div', 'ap-meta', candidate.reason));
            list.appendChild(row);
        }
        section.appendChild(list);
        this.body.appendChild(section);
    }

    renderActions() {
        const actions = el('div', 'ap-actions ap-actions-sticky');
        actions.appendChild(this.button('再讲一点', '追加更多阶段解读', () => this.runAi('expand'), { warm: true }));
        actions.appendChild(this.button('补支线', '生成一张轻量支线卡', () => this.runAi('branch')));
        actions.appendChild(this.button('补死法', '生成几个死法候选', () => this.runAi('death')));
        actions.appendChild(this.button('补候选', '生成可审核候选素材', () => this.runAi('candidates')));
        actions.appendChild(this.button('复制分享', '复制截图分享语', () => copyText(this.state.share), { disabled: !this.state.share }));
        actions.appendChild(this.button('复制全部', '复制当前 AI 插件内容', () => copyText(this.bundleText()), { disabled: !this.state.latest }));
        this.body.appendChild(actions);
    }

    renderMeta() {
        if (!this.state.lastMeta) return;
        const provider = this.state.lastMeta.provider || 'model';
        const model = this.state.lastMeta.model || '';
        this.body.appendChild(el('div', 'ap-meta ap-meta-bottom', `${provider}${model ? ` · ${model}` : ''}`));
    }

    bundleText() {
        return [
            `旁白：${this.state.narration}`,
            `复盘：${this.state.recap}`,
            `分享：${this.state.share}`,
            `属性：${this.state.delta}`,
            `支线：${this.state.branch}`,
            ...this.state.extra.map(item => `${item.title || item.kind}：${item.text || item.description || ''}`),
            ...this.state.deaths.map(item => `${item.title || item.kind}：${item.text || item.description || ''}`),
            ...this.state.candidates.map(item => `${item.title || item.kind}：${item.text || item.description || ''}`),
        ].filter(Boolean).join('\n\n');
    }
}

export function installAgentAiPlugin() {
    if (globalThis.__agentAiPlugin) return;
    const panel = new AgentAiPluginPanel();
    globalThis.__agentAiPlugin = panel;

    $$on('agent-life-reset', () => panel.reset());
    $$on('agent-life-step', payload => panel.updateFromStep(payload));
}
