export class AgentAiPluginState {
    constructor() {
        this.reset();
    }

    reset() {
        this.runId = `ai_run_${Date.now()}`;
        this.timeline = [];
        this.latest = null;
        this.summary = null;
        this.ended = false;
        this.narration = '';
        this.recap = '';
        this.share = '';
        this.delta = '';
        this.branch = '';
        this.extra = [];
        this.deaths = [];
        this.candidates = [];
        this.lastMeta = null;
        this.autoGeneratedFor = null;
    }

    addStep(ir, summary) {
        if (!ir) return;
        this.timeline.push(ir);
        this.latest = ir;
        if (ir.isEnd) this.ended = true;
        if (summary) this.summary = summary;
    }

    context() {
        const recent = this.timeline.slice(-8).map(item => ({
            age: item.age,
            stage: item.stage,
            text: item.text,
            tags: item.tags,
            coreStats: item.coreStats,
            isEnd: item.isEnd,
        }));

        return {
            runId: this.runId,
            latest: this.latest ? {
                age: this.latest.age,
                stage: this.latest.stage,
                text: this.latest.text,
                tags: this.latest.tags,
                coreStats: this.latest.coreStats,
                isEnd: this.latest.isEnd,
            } : null,
            recent,
            ended: this.ended,
            summary: this.summary,
            productTone: '中文互联网原生、轻快、有梗、像 Agent 人生模拟器，不要翻译腔。',
        };
    }

    latestKey() {
        if (!this.latest) return '';
        return `${this.latest.runId}:${this.latest.age}:${this.latest.text}`;
    }
}
